# Generated by Django 4.2.8 on 2023-12-16 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('monthly_salary', models.IntegerField()),
                ('approved_limit', models.IntegerField()),
                ('age', models.IntegerField()),
                ('current_debt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanInfo',
            fields=[
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backendapi.customersinfo')),
                ('loan_id', models.CharField(max_length=100)),
                ('loan_amount', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('tenure', models.IntegerField()),
                ('monthly_repayment', models.IntegerField()),
                ('emi_on_time', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
