# Generated by Django 4.2.8 on 2023-12-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersinfo',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customersinfo',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customersinfo',
            name='current_debt',
            field=models.IntegerField(default=0),
        ),
    ]
