# Generated by Django 4.2.8 on 2023-12-17 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0002_rename_name_customersinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninfo',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backendapi.customersinfo'),
        ),
        migrations.AlterField(
            model_name='loaninfo',
            name='loan_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
