# Generated by Django 4.2.8 on 2023-12-17 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0003_alter_loaninfo_customer_id_alter_loaninfo_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninfo',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='backendapi.customersinfo'),
        ),
    ]
