# Generated by Django 4.2.8 on 2023-12-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0004_alter_loaninfo_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersinfo',
            name='approved_limit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customersinfo',
            name='monthly_salary',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customersinfo',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
